<a href="https://colab.research.google.com/github/hch507/tic-tac-toe-AI_game/blob/main/tic_tac_toe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import io

In [2]:
from google.colab import files

In [3]:
file = files.upload()

Saving tic-tac-toe-endgame.csv to tic-tac-toe-endgame.csv


In [4]:
tic_df = pd.read_csv(io.BytesIO(file['tic-tac-toe-endgame.csv']))

In [5]:
tic_df

V1 V2 V3 V4 V5 V6 V7 V8 V9       V10
0    x  x  x  x  o  o  x  o  o  positive
1    x  x  x  x  o  o  o  x  o  positive
2    x  x  x  x  o  o  o  o  x  positive
3    x  x  x  x  o  o  o  b  b  positive
4    x  x  x  x  o  o  b  o  b  positive
..  .. .. .. .. .. .. .. .. ..       ...
953  o  x  x  x  o  o  o  x  x  negative
954  o  x  o  x  x  o  x  o  x  negative
955  o  x  o  x  o  x  x  o  x  negative
956  o  x  o  o  x  x  x  o  x  negative
957  o  o  x  x  x  o  o  x  x  negative

[958 rows x 10 columns]

In [6]:
tic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   V1      958 non-null    object
 1   V2      958 non-null    object
 2   V3      958 non-null    object
 3   V4      958 non-null    object
 4   V5      958 non-null    object
 5   V6      958 non-null    object
 6   V7      958 non-null    object
 7   V8      958 non-null    object
 8   V9      958 non-null    object
 9   V10     958 non-null    object
dtypes: object(10)
memory usage: 75.0+ KB


In [7]:
tic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   V1      958 non-null    object
 1   V2      958 non-null    object
 2   V3      958 non-null    object
 3   V4      958 non-null    object
 4   V5      958 non-null    object
 5   V6      958 non-null    object
 6   V7      958 non-null    object
 7   V8      958 non-null    object
 8   V9      958 non-null    object
 9   V10     958 non-null    object
dtypes: object(10)
memory usage: 75.0+ KB


In [8]:
tic_df['V1'].value_counts()

x    418
o    335
b    205
Name: V1, dtype: int64

In [9]:
##features =['V1','V2','V3','V4','V5','V6','V7','V8','V9','V10']
##for feature in features:
tic_np = tic_df.values  
print(tic_np.dtype)

object


In [10]:
for i in range(958):
  for f in range(10):
    if(tic_np[i][f] =='x'):
      tic_np[i][f]=1
    if(tic_np[i][f] =='o'):
      tic_np[i][f]=0
    if(tic_np[i][f] =='b'):
      tic_np[i][f]=2
    if(tic_np[i][f] =='positive'):
      tic_np[i][f]=1
    if(tic_np[i][f] =='negative'):
      tic_np[i][f]=0

print(tic_np)


[[1 1 1 ... 0 0 1]
 [1 1 1 ... 1 0 1]
 [1 1 1 ... 0 1 1]
 ...
 [0 1 0 ... 0 1 0]
 [0 1 0 ... 0 1 0]
 [0 0 1 ... 1 1 0]]


In [11]:
import tensorflow as tf

In [12]:
test_rate = 0.2

n = int(tic_np.shape[0]*(1-test_rate))
print(n)

766


In [13]:
x_train = tic_np[ : n, :-1].astype(int)
y_train = tic_np[ : n, -1].astype(int)

x_test = tic_np[n: , :-1].astype(int)
y_test = tic_np[n: , -1].astype(int)

print(f'x_train 의 개수 : { x_train.shape[0]}')
print(f'y_train 의 개수 : { y_train.shape[0]}')
print(f'x_test 의 개수 : { x_test.shape[0]}')
print(f'y_test 의 개수 : { x_test.shape[0]}')

x_train 의 개수 : 766
y_train 의 개수 : 766
x_test 의 개수 : 192
y_test 의 개수 : 192


In [14]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(units=150, input_dim = 9, activation="relu"))
model.add(tf.keras.layers.Dense(units=150, activation="relu"))
model.add(tf.keras.layers.Dense(units=150, activation="relu"))
model.add(tf.keras.layers.Dense(units=1,  activation="sigmoid"))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 150)               1500      
                                                                 
 dense_1 (Dense)             (None, 150)               22650     
                                                                 
 dense_2 (Dense)             (None, 150)               22650     
                                                                 
 dense_3 (Dense)             (None, 1)                 151       
                                                                 
Total params: 46,951
Trainable params: 46,951
Non-trainable params: 0
_________________________________________________________________


In [15]:
opt = tf.keras.optimizers.SGD(learning_rate = 0.2)
model.compile(optimizer = opt, loss = 'mse', metrics=['accuracy'])

In [16]:
ret = model.fit(x_train, y_train, epochs=100)
print(f'model.layer = {len(model.layers)}')


Epoch 1/100
24/24 [==============================] - 1s 3ms/step - loss: 0.1491 - accuracy: 0.8133
Epoch 2/100
24/24 [==============================] - 0s 2ms/step - loss: 0.1374 - accuracy: 0.8172
Epoch 3/100
24/24 [==============================] - 0s 3ms/step - loss: 0.1341 - accuracy: 0.8172
Epoch 4/100
24/24 [==============================] - 0s 3ms/step - loss: 0.1302 - accuracy: 0.8172
Epoch 5/100
24/24 [==============================] - 0s 3ms/step - loss: 0.1267 - accuracy: 0.8172
Epoch 6/100
24/24 [==============================] - 0s 3ms/step - loss: 0.1232 - accuracy: 0.8185
Epoch 7/100
24/24 [==============================] - 0s 2ms/step - loss: 0.1203 - accuracy: 0.8225
Epoch 8/100
24/24 [==============================] - 0s 2ms/step - loss: 0.1181 - accuracy: 0.8198
Epoch 9/100
24/24 [==============================] - 0s 3ms/step - loss: 0.1122 - accuracy: 0.8342
Epoch 10/100
24/24 [==============================] - 0s 3ms/step - loss: 0.1085 - accuracy: 0.8460
Epoch 11/