<a href="https://colab.research.google.com/github/hch507/tic-tac-toe-AI_game/blob/main/tic_tac_toe_DNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import io

In [2]:
from google.colab import files

In [3]:
file = files.upload()

Saving tic-tac-toe-endgame.csv to tic-tac-toe-endgame.csv


In [4]:
tic_df = pd.read_csv(io.BytesIO(file['tic-tac-toe-endgame.csv']))

In [5]:
tic_df

V1 V2 V3 V4 V5 V6 V7 V8 V9       V10
0    x  x  x  x  o  o  x  o  o  positive
1    x  x  x  x  o  o  o  x  o  positive
2    x  x  x  x  o  o  o  o  x  positive
3    x  x  x  x  o  o  o  b  b  positive
4    x  x  x  x  o  o  b  o  b  positive
..  .. .. .. .. .. .. .. .. ..       ...
953  o  x  x  x  o  o  o  x  x  negative
954  o  x  o  x  x  o  x  o  x  negative
955  o  x  o  x  o  x  x  o  x  negative
956  o  x  o  o  x  x  x  o  x  negative
957  o  o  x  x  x  o  o  x  x  negative

[958 rows x 10 columns]

In [6]:
tic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   V1      958 non-null    object
 1   V2      958 non-null    object
 2   V3      958 non-null    object
 3   V4      958 non-null    object
 4   V5      958 non-null    object
 5   V6      958 non-null    object
 6   V7      958 non-null    object
 7   V8      958 non-null    object
 8   V9      958 non-null    object
 9   V10     958 non-null    object
dtypes: object(10)
memory usage: 75.0+ KB


In [7]:
tic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958 entries, 0 to 957
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   V1      958 non-null    object
 1   V2      958 non-null    object
 2   V3      958 non-null    object
 3   V4      958 non-null    object
 4   V5      958 non-null    object
 5   V6      958 non-null    object
 6   V7      958 non-null    object
 7   V8      958 non-null    object
 8   V9      958 non-null    object
 9   V10     958 non-null    object
dtypes: object(10)
memory usage: 75.0+ KB


In [8]:
tic_df['V1'].value_counts()

x    418
o    335
b    205
Name: V1, dtype: int64

In [9]:
##features =['V1','V2','V3','V4','V5','V6','V7','V8','V9','V10']
##for feature in features:
tic_np = tic_df.values  
print(tic_np.dtype)

object


In [10]:
for i in range(958):
  for f in range(10):
    if(tic_np[i][f] =='x'):
      tic_np[i][f]=1
    if(tic_np[i][f] =='o'):
      tic_np[i][f]=0
    if(tic_np[i][f] =='b'):
      tic_np[i][f]=2
    if(tic_np[i][f] =='positive'):
      tic_np[i][f]=1
    if(tic_np[i][f] =='negative'):
      tic_np[i][f]=0

print(tic_np)


[[1 1 1 ... 0 0 1]
 [1 1 1 ... 1 0 1]
 [1 1 1 ... 0 1 1]
 ...
 [0 1 0 ... 0 1 0]
 [0 1 0 ... 0 1 0]
 [0 0 1 ... 1 1 0]]


In [54]:
np.random.shuffle(tic_np)
tic_np[766: , -1]

array([1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0], dtype=object)

In [55]:
import tensorflow as tf

In [57]:
test_rate = 0.2

n = int(tic_np.shape[0]*(1-test_rate))
print(n)

766


In [58]:
x_train = tic_np[ : n, :-1].astype(int)
y_train = tic_np[ : n, -1].astype(int)

x_test = tic_np[n: , :-1].astype(int)
y_test = tic_np[n: , -1].astype(int)

print(f'x_train 의 개수 : { x_train.shape[0]}')
print(f'y_train 의 개수 : { y_train.shape[0]}')
print(f'x_test 의 개수 : { x_test.shape[0]}')
print(f'y_test 의 개수 : { x_test.shape[0]}')

x_train 의 개수 : 766
y_train 의 개수 : 766
x_test 의 개수 : 192
y_test 의 개수 : 192


In [60]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(units=2000, input_dim = 9, activation="relu"))
model.add(tf.keras.layers.Dense(units=1000, activation="relu"))
model.add(tf.keras.layers.Dense(units=500, activation="relu"))
model.add(tf.keras.layers.Dense(units=300, activation="relu"))
model.add(tf.keras.layers.Dense(units=1,  activation="sigmoid"))
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_16 (Dense)            (None, 2000)              20000     
                                                                 
 dense_17 (Dense)            (None, 1000)              2001000   
                                                                 
 dense_18 (Dense)            (None, 500)               500500    
                                                                 
 dense_19 (Dense)            (None, 300)               150300    
                                                                 
 dense_20 (Dense)            (None, 1)                 301       
                                                                 
Total params: 2,672,101
Trainable params: 2,672,101
Non-trainable params: 0
_________________________________________________________________


In [61]:
opt = tf.keras.optimizers.SGD(learning_rate = 0.2)
model.compile(optimizer = opt, loss = 'mse', metrics=['accuracy'])

In [62]:
ret = model.fit(x_train, y_train, epochs=100 )
print(f'model.layer = {len(model.layers)}')


Epoch 1/100
24/24 [==============================] - 1s 28ms/step - loss: 0.2222 - accuracy: 0.6567
Epoch 2/100
24/24 [==============================] - 1s 28ms/step - loss: 0.2084 - accuracy: 0.6632
Epoch 3/100
24/24 [==============================] - 1s 27ms/step - loss: 0.1999 - accuracy: 0.6775
Epoch 4/100
24/24 [==============================] - 1s 27ms/step - loss: 0.1931 - accuracy: 0.6997
Epoch 5/100
24/24 [==============================] - 1s 28ms/step - loss: 0.1854 - accuracy: 0.7076
Epoch 6/100
24/24 [==============================] - 1s 27ms/step - loss: 0.1791 - accuracy: 0.7102
Epoch 7/100
24/24 [==============================] - 1s 28ms/step - loss: 0.1733 - accuracy: 0.7272
Epoch 8/100
24/24 [==============================] - 1s 27ms/step - loss: 0.1701 - accuracy: 0.7480
Epoch 9/100
24/24 [==============================] - 1s 27ms/step - loss: 0.1680 - accuracy: 0.7337
Epoch 10/100
24/24 [==============================] - 1s 28ms/step - loss: 0.1446 - accuracy: 0.7768

In [63]:
score = model.evaluate(x_test, y_test)

6/6 [==============================] - 0s 7ms/step - loss: 0.0290 - accuracy: 0.9688


In [64]:
print(f'loss값 : {score[0]} 정답률 :{score[1]} ')

loss값 : 0.028984539210796356 정답률 :0.96875 


In [72]:
predict = model.predict(x_test)

In [73]:
predict

array([[0.9999993 ],
       [0.00926805],
       [0.9999652 ],
       [0.0129036 ],
       [0.9985486 ],
       [0.88638407],
       [0.00613341],
       [1.        ],
       [0.01988432],
       [0.99997604],
       [0.9999194 ],
       [0.00211301],
       [0.9986454 ],
       [0.9999995 ],
       [0.94801027],
       [0.99744534],
       [0.07020462],
       [0.994123  ],
       [0.00506052],
       [0.9315778 ],
       [0.99413127],
       [1.        ],
       [0.9987947 ],
       [1.        ],
       [0.15036309],
       [0.02255392],
       [0.27867642],
       [0.02499884],
       [0.01032707],
       [0.99999136],
       [0.68173057],
       [0.46512252],
       [0.53449225],
       [0.9999744 ],
       [0.01759645],
       [0.01390052],
       [0.04735568],
       [0.01216802],
       [0.99997926],
       [0.99989295],
       [0.00160497],
       [0.99993104],
       [0.99981415],
       [0.9594424 ],
       [0.9999676 ],
       [0.9999596 ],
       [0.99215394],
       [0.998

In [74]:
for i in range(192):
  if predict[i]>=0.5:
    predict[i]=1
  elif predict[i]<0.5:
    predict[i]=0

print(predict)

[[1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.

In [75]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, predict)

array([[ 69,   5],
       [  1, 117]])